name: Transfer Repository to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install any dependencies if required

      - name: Transfer repository to EC2
        uses: appleboy/scp-action@master
        with:
          host: dpu.journalchecker.com
          username: ubuntu
          password: admin@10
          source: ./
          target: /home/ubuntu/sites/rims/
