name: Transfer Repository to EC2 ( dpu.journalchecker.com )

on:
  push:
    branches:
      - main
      - L2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install any dependencies if required

      - name: Transfer repository to EC2
        uses: appleboy/scp-action@master
        with:
          host: dpu.journalchecker.com
          username: ubuntu
          password: admin@10
          source: ./
          target: /home/ubuntu/sites/rims/
      - name: Logging into SSH
        uses: appleboy/ssh-action@master
        with:
          host: dpu.journalchecker.com
          username: ubuntu
          password: admin@10
          script: |
            cd sites/rims/
            source ~/.nvm/nvm.sh
            nvm use v18
            npm run build
            pm2 restart rims
